---
services:
  grafana:
    user: root
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    container_name: grafana
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
 
  loki:
    image: grafana/loki:latest
    container_name: loki-app
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - ./loki/conf/local-config.yaml:/etc/loki/local-config.yaml
      - ./loki/data:/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml