global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'prometheus_master'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter_wordpress'
    static_configs:
      - targets: ['wordpress:9100']
  - job_name: 'mysqld'
    static_configs:
      - targets: ['wordpress:9104']
  - job_name: 'blackbox_check_wordpress'
    metrics_path: /probe
    params:
      module:
        - http_2xx
    static_configs:
      - targets:
        - mysite.local
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - replacement: wordpress:9115
      target_label: __address__
  - job_name: "nginx_exporter"
    static_configs:
      - targets: ['wordpress:9113']
  - job_name: "php-fpm_exporter"
    static_configs:
      - targets: ['wordpress:8080']
