version: '3'

services:
  filebeat:
    image: elastic/filebeat:8.19.4 
    container_name: filebeat
    restart: unless-stopped
    user: root
    environment:
      - LOGSTASH_HOSTS=logstash.local:5044
    volumes:
      - /var/log/:/var/log/hostlog/
      - ./conf/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    extra_hosts:
      - "logstash.local:192.168.250.22"
  metricbeat:
    image: elastic/metricbeat:8.19.4
    container_name: metricbeat
    restart: unless-stopped
    user: root
    volumes:
      - ./conf/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostfs:ro
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
    environment:
    #  - ELASTIC_USER=elastic
    #  - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
     - ELASTIC_HOSTS=http://elastic.local:9200
     - KIBANA_HOSTS=http://elastic.local:5601
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "mysite.local:host-gateway"
      - "elastic.local:192.168.250.22"
