filebeat.modules:
- module: nginx
  access:
    enabled: true
    var.paths: ["/var/log/hostlog/nginx/access.log*"]
  error:
    enabled: true
    var.paths: ["/var/log/hostlog/nginx/.log*"]
- module: mysql
  error:
    enabled: true
    var.paths: ["/var/log/hostlog/mariadb/mariadb.log"]
  slowlog:
    enabled: true
    var.paths: ["/var/log/hostlog/mariadb/*slow.log*"]    
# - module: system
#   syslog:
#     enabled: true
#     var.use_journald: true
#   auth:
#     enabled: true
#     var.use_journald: true

filebeat.inputs:
- type: log
  id: php-fm
  enabled: true
  paths:
    - /var/log/hostlog/php-fm/*.log
output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS}'
  # username: '${ELASTICSEARCH_USERNAME:}'
  # password: '${ELASTICSEARCH_PASSWORD:}'
